/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCaixaRouteImport } from './routes/app/caixa'
import { Route as AppClientesRouteImport } from './routes/app/clientes'
import { Route as AppComprasRouteImport } from './routes/app/compras'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppCrmRouteImport } from './routes/app/crm'
import { Route as AppDevolucoesRouteImport } from './routes/app/devolucoes'
import { Route as AppEstoqueRouteImport } from './routes/app/estoque'
import { Route as AppFinanceiroRouteImport } from './routes/app/financeiro'
import { Route as AppFornecedoresRouteImport } from './routes/app/fornecedores'
import { Route as AppMetasRouteImport } from './routes/app/metas'
import { Route as AppPdvRouteImport } from './routes/app/pdv'
import { Route as AppProdutosRouteImport } from './routes/app/produtos'
import { Route as AppPromocoesRouteImport } from './routes/app/promocoes'
import { Route as AppRelatoriosRouteImport } from './routes/app/relatorios'
import { Route as AppVendasRouteImport } from './routes/app/vendas'
import { Route as AppVendedoresRouteImport } from './routes/app/vendedores'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCaixaRoute = AppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevolucoesRoute = AppDevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPromocoesRoute = AppPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendedoresRoute = AppVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/devolucoes': typeof AppDevolucoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/metas': typeof AppMetasRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/promocoes': typeof AppPromocoesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/devolucoes': typeof AppDevolucoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/metas': typeof AppMetasRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/promocoes': typeof AppPromocoesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/crm': typeof AppCrmRoute
  '/app/devolucoes': typeof AppDevolucoesRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fornecedores': typeof AppFornecedoresRoute
  '/app/metas': typeof AppMetasRoute
  '/app/pdv': typeof AppPdvRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/promocoes': typeof AppPromocoesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/vendedores': typeof AppVendedoresRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/caixa'
    | '/app/clientes'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/devolucoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/metas'
    | '/app/pdv'
    | '/app/produtos'
    | '/app/promocoes'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app/vendedores'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/caixa'
    | '/app/clientes'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/devolucoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/metas'
    | '/app/pdv'
    | '/app/produtos'
    | '/app/promocoes'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app/vendedores'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/caixa'
    | '/app/clientes'
    | '/app/compras'
    | '/app/configuracoes'
    | '/app/crm'
    | '/app/devolucoes'
    | '/app/estoque'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/metas'
    | '/app/pdv'
    | '/app/produtos'
    | '/app/promocoes'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app/vendedores'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/caixa': {
      id: '/app/caixa'
      path: '/caixa'
      fullPath: '/app/caixa'
      preLoaderRoute: typeof AppCaixaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/compras': {
      id: '/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/devolucoes': {
      id: '/app/devolucoes'
      path: '/devolucoes'
      fullPath: '/app/devolucoes'
      preLoaderRoute: typeof AppDevolucoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fornecedores': {
      id: '/app/fornecedores'
      path: '/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pdv': {
      id: '/app/pdv'
      path: '/pdv'
      fullPath: '/app/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/produtos': {
      id: '/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/promocoes': {
      id: '/app/promocoes'
      path: '/promocoes'
      fullPath: '/app/promocoes'
      preLoaderRoute: typeof AppPromocoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendedores': {
      id: '/app/vendedores'
      path: '/vendedores'
      fullPath: '/app/vendedores'
      preLoaderRoute: typeof AppVendedoresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppCaixaRoute: typeof AppCaixaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppComprasRoute: typeof AppComprasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDevolucoesRoute: typeof AppDevolucoesRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPdvRoute: typeof AppPdvRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppPromocoesRoute: typeof AppPromocoesRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVendasRoute: typeof AppVendasRoute
  AppVendedoresRoute: typeof AppVendedoresRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCaixaRoute: AppCaixaRoute,
  AppClientesRoute: AppClientesRoute,
  AppComprasRoute: AppComprasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCrmRoute: AppCrmRoute,
  AppDevolucoesRoute: AppDevolucoesRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppMetasRoute: AppMetasRoute,
  AppPdvRoute: AppPdvRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppPromocoesRoute: AppPromocoesRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVendasRoute: AppVendasRoute,
  AppVendedoresRoute: AppVendedoresRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
